# Generated by Django 3.1.2 on 2020-10-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, unique=True)),
                ('path', models.SlugField(max_length=200, unique=True)),
                ('authors', models.JSONField(default='')),
                ('article_type', models.CharField(max_length=200)),
                ('promo', models.CharField(default='', max_length=200)),
                ('disclosure', models.TextField()),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('instruments', models.JSONField(default='')),
                ('bureau', models.JSONField(default='')),
                ('collection', models.JSONField(default='')),
                ('tags', models.JSONField(default='')),
                ('recommendations', models.JSONField(default='')),
                ('images', models.JSONField(default='')),
                ('video', models.CharField(blank=True, max_length=200, null=True)),
                ('pitch', models.JSONField(default='')),
                ('links', models.JSONField(default='')),
                ('byline', models.JSONField(default='')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
