# Generated by Django 3.1.2 on 2020-10-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='bureau',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='collection',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='instruments',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='pitch',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='recommendations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
