# Generated by Django 3.1.2 on 2020-10-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20201011_0613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated_on',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='article',
            name='author_override',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='static_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='uuid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.IntegerField(default=100),
        ),
    ]
