# Generated by Django 3.1.2 on 2020-10-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20201011_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='bureau',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='collection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='instruments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='pitch',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='recommendations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
