# Generated by Django 3.1.2 on 2020-10-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20201011_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='path',
            new_name='slug',
        ),
    ]
