# Generated by Django 3.1.2 on 2020-10-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
