# Generated by Django 3.1.2 on 2020-10-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_auto_20201011_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=10)),
                ('exchange_name', models.CharField(max_length=50)),
                ('instrument_id', models.IntegerField()),
                ('change', models.FloatField()),
                ('current_price', models.FloatField()),
                ('percent_change', models.FloatField()),
                ('website', models.URLField()),
            ],
        ),
    ]
